development:
  adapter: postgresql
  database: mozap
  username: codyjames408
  password:
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: mozap
  username: codyjames408
  password:
  pool: 5
  timeout: 5000
